### ISSUE TITLE
Different Tooltip Types

### ISSUE THREAD

**Issue by yodem** [oVirt/ovirt-web-ui#1094]
In the VM Details page, they are different types of tooltips, and i think we should decide what tooltip do we want.
![TooltipPush](https://user-images.githubusercontent.com/13103729/63339981-bb5fe480-c34e-11e9-9b03-d34cf2d340b7.png)
![Tooltip type3](https://user-images.githubusercontent.com/13103729/63339983-bb5fe480-c34e-11e9-90db-a7c28728729a.png)
![Tooltip type 2](https://user-images.githubusercontent.com/13103729/63339984-bbf87b00-c34e-11e9-9f24-c0b913a3d1a6.png)
![Tooltips types4](https://user-images.githubusercontent.com/13103729/63340101-f3ffbe00-c34e-11e9-906d-441b9fe0a46f.png)

@lwrigh what do you think we need to do?

**Comment by lwrigh** [comment]
@yodem I think in this case since we're starting to migrate over to PatternFly 4 we should use the PatternFly 4 style of tooltips: 
<img width="165" alt="Screen Shot 2019-08-20 at 9 54 57 AM" src="https://user-images.githubusercontent.com/20227374/63353335-96f50f80-c330-11e9-8af2-282087305821.png">

https://www.patternfly.org/v4/documentation/react/components/tooltip/#simple-tooltip

**Comment by sjd78** [comment]
@yodem , @lwrigh : To split some hairs, those are Tooltips and Field level help boxes.

Quick look at PF4 still shows a distinction...
 - Tooltips:
    - couldn't find design guidelines
    - https://www.patternfly.org/v4/documentation/react/components/tooltip/
 - Form field help:
    - https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/forms/#provide-the-right-kind-of-help
    - https://www.patternfly.org/v4/documentation/react/components/popover/

I'm all for all of the tooltips using the same component (instead of overlaytrigger/tooltip or the title attribute on tags).  I'm just not sure that the field help and tooltip should look the same, especially since tooltips are on hover while the help is on click (usually).

**Comment by yodem** [comment]
@lwrigh 
So maybe we can turn the help button to be a tooltip of an help icon?

**Comment by lwrigh** [comment]
@sjd78 @yodem I think if we're transitioning these info tips over to PF4 we should probably transition over the icon as well since PF4 uses the question mark icon as the icon for help text. Here's the example that features it: 
https://www.patternfly.org/v4/static/8526d9705b44d5485cb3c6521e073b8c/1e1f5/popover.png

**Comment by yodem** [comment]
Ok so to sum it up:
 - Wherever there is a tooltip we need to turn it into a PF4 tooltip as you can see here  -https://github.com/oVirt/ovirt-web-ui/issues/1094#issuecomment-523026344

 - Wherever there is a Form field help we need to turn it into a PF4 question mark - 
https://www.patternfly.org/v4/static/8526d9705b44d5485cb3c6521e073b8c/1e1f5/popover.png

@sjd78 @sgratch @lwrigh Everyones agrees?

**Comment by lwrigh** [comment]
Yup that sounds good to me!

**Comment by sgratch** [comment]
@yodem @lwrigh @sjd78  
LGTM,
Yet few issues I'm not sure about:
**For help tooltips** - need to decide where is the question mark icon located. Is it right next to the field name (constant layout) or next to the value?  Current layout is not consistent.
**Regarding regular (non help) tooltips** - how do we mark simple tooltips and how do we mark tooltips on icons? we have both...(see snapshot->detailes->show more tooltip).
**For both** - what is the popover position for both tooltip types (currently we have few positions for each type).

**Comment by lwrigh** [comment]
For help tool tips, I would suggest adding the question mark icon next to the field name. 

For simple tooltips and tooltips on icons, it's more up to the user to discover them. PF features a focus state once the user has revealed the tooltip. https://www.patternfly.org/v4/documentation/react/components/tooltip/#tooltip-title 

For the the position of both, it's pretty layout and situation specific for which direction the tooltip goes in. As a rule of thumb, it's probably best to pick a direction where the tooltip does not overlap too much with other buttons, text, or navigation. It also depends on if the tooltip is close to the edge of the browser window.
