### ISSUE TITLE
Show FC path status like the network card

### ISSUE THREAD

**Issue by Mad1969it** [oVirt/ovirt-web-ui#1153]
Hello,
I want to ask an RFE, it's possible to ad in the portal on the tab Host the status of the FC path like the network card.
This can help is i have a problem in one or more path exactly like the NIC
Regards
Massimo

**Comment by sgratch** [comment]
This seems like a webadmin issue. There is no host tab/settings on web-ui and storage path is less relevant for web-ui users since they can't edit/create storage domains. 
webadmin tracks issues at https://bugzilla.redhat.com

I'm closing this ticket since it's old anyway. If it's sill relevant, please file a bug.
