### ISSUE TITLE
Add a "Share with..." option for VMs in the VM portal

### ISSUE THREAD

**Issue by nkovacne** [oVirt/ovirt-web-ui#1160]
Feature enhancement request:

I'm aware that the new VM portal (since 4.2) is implemented under the "keep it simple" principle, and that's why the "Permissions" option has been removed.

However, it would be nice if there could be an option to grant the "UserRole" permission on some machine to a user. We use this a lot since we have a lot of courses in our University where a VM is owned by a group, not a single person. In this case, the creator used to grant the UserRole permission on the rest of the group.

To keep the "keep it simple" principle, this feature could be implemented like a "Share VM with...", then the owner would be capable of choose with whom to share, and internally the UserRole permission would be applied. Also, a "Stop sharing with..." option would be necessarily be implemented.

**Comment by sgratch** [comment]
@nkovacne sorry for the late response.
IIUC you are asking for an option to grant user/group permission while creating a VM via the web-ui. Please correct me if I'm wrong.

In general, the VM portal is used by specific users that were granted with permissions only by the admin user via the admin portal and therefore we are not supporting any permissions management or granting via the VM portal. If a user requires a specific permission then he should refer to the admin user for that.

Anyway, whenever you create a VM based on a template via the VM portal, the template Permissions (users and groups) are automatically copied to that created VM.

So as a workaround, I can suggest you the following solution for creating a VM with a specific permissions without the need to ask the admin per each VM's creation:
The admin can create a template via admin portal per each set of permissions that you would like and then users can just create a VM via VM portal that is based on that specific template for granting all its permissions.

I'm closing this issue since we are not going to implement it. Please re-open if you need more help or if the issue was not well understood by me.
