### ISSUE TITLE
Create VM Wizard - Storage step - enable setting/unsetting disks as bootable

### ISSUE THREAD

**Issue by sgratch** [oVirt/ovirt-web-ui#1199]
Disks should be set/unset as Bootable in Storage step of Create VM wizard.
Also, the first added disk should be set as Bootable by default.

We added this feature to "edit VM" flow #1103 and now we should support that for "create VM" as well.
Note that in case this flag is taken of a template's disk then we should updated disks as appropriate

**Comment by hstastna** [comment]
@sgratch @lwrigh @michalskrivanek There's a bunch of UX things I would like to talk about regarding enabling setting/unsetting disks as bootable feature, not only in the Storage step, but also when adding/editing Disks for an existing VM:

**1.** I don't know how we'd like to display the bootable option in the Storage step when adding/editing a Disk, so a couple of possibilities came to my mind. For example:
a) displaying the checkbox together with the 'Bootable' label **under the list/table of Disks** (similarly as it is already when editing an existing VM's Disks in our web UI), 
![bootable_under2](https://user-images.githubusercontent.com/13417815/83773063-5dee1780-a684-11ea-8656-9a33f1ae5861.png)
  - Later, we could add more options there. They would disappear after user was satisfied and saved the change.

b) or **next to the table of Disks** - similarly as it is in webadmin (where Bootable option is next to the other options):
![edit_disk_webadmin](https://user-images.githubusercontent.com/13417815/83775513-4f552f80-a687-11ea-9b58-2311a17cf68c.png)
c) displaying the checkbox **in the new column** for a new/edited Disk (for Disks which are just displayed, there's already "bootable" label displayed next to the Disk Name):
![boot_column](https://user-images.githubusercontent.com/13417815/83776769-dce54f00-a688-11ea-8516-95ec69f84b78.png)

  - I would go for the last (c) option as I think it's the best one.

---

**2.** I think the last column for Disks takes too much space and in some cases, there have to be 2 lines in the row because of not enough space for example for "select a Storage Domain":
![storage_domain](https://user-images.githubusercontent.com/13417815/83778032-6f3a2280-a68a-11ea-9714-8f11a561cff2.png)
  - Less space for the last column would mean more space for the Bootable column and also for Storage Domain column. Maybe we should reconsider the width of the columns. I think it does not look very good now. And maybe the last column could be "invisible" column (and info tooltip + "..." for edit and delete options could be there as they are, just looking like being out of the table) - I think this would look better. When editing Disks for an existing VM, there isn't any visible table.

---

**3.** The three vertical dots for expanding the edit and delete options for a disk - this is just extra clicking:
![storage_step_actual](https://user-images.githubusercontent.com/13417815/83783176-59c7f700-a690-11ea-9449-d4ab6a78757f.png)
  - I think we really don't need it like this. We could use edit (pencil) and delete (bin) icons there instead, the same as it is for editing disks for an existing VM:
![edit_delete](https://user-images.githubusercontent.com/13417815/83779194-ede38f80-a68b-11ea-8bb2-8a4aec6cd0e9.png)
  With such a change, we would make things more consistent and not displaying the same things differently in different places across the same UI.

---

**4.** Just another idea, I think it would be nice to have the bin icon for deleting a Disk for an existing VM in a red color. It would distinguish Edit and Delete icons better and also it would be more consistent with the red _Remove_ button up right - for deleting an existing VM. I often made a mistake and clicked on edit icon instead of remove and the opposite, when I was making familiar with Disks for some existing VM. Maybe it could look like this:
![red_bin](https://user-images.githubusercontent.com/13417815/83782291-e4f4bd00-a68f-11ea-918f-685a668ae1ce.png)

**Comment by sgratch** [comment]
@hstastna  @lwrigh @michalskrivanek @sjd78 
I agree with all those suggestions done by Hilda (including choosing option (c) for adding the bootable column) but I'm not familiar with the original create vm wizard design considerations, so need Laura and Scott for that.
We also need to consider compatibility with Pattternfly 4 in case of changes.

We can start with adding the bootable column which is required for this issue and open separate issues for all other suggestions in case we'll agree to do them.

**Comment by michalskrivanek** [comment]
let's go with (c)

the other suggestions are also good. Not too important, but if you can easily fix them then go for it.

**Comment by sjd78** [comment]
@hstastna - Yeah **1c** looks like a solid plan for the bootable flag at create.  It'll be interesting to see the column comes and goes with the edit state.  Putting a "Make Disk Bootable" as an action on the kebab menu is also a good option to change an existing disk without having to turn on edit, click bootable and then save it.  Shouldn't be much work to do both.

For **2** - the column widths are a bit tricky with the PF3 table component.  If you can get it to be consistent, go for it.

For **3** - that is a design decision to have the actions under the kebab instead of a set of edit/delete icons on each row.  Here is the original design doc for your reference:
  - https://docs.google.com/document/d/1UtFhNa_1byMV5mLEJ1MbdvZj-uMpmsD-_bJ37JDcyjU

For **4** - sure that makes sense, but done in another issue so it can be applied to snapshots, nics and disks on the VM details page.  And there is a particular red color to be referenced as well.

**Comment by sgratch** [comment]
> @hstastna - Yeah **1c** looks like a solid plan for the bootable flag at create. It'll be interesting to see the column comes and goes with the edit state. Putting a "Make Disk Bootable" as an action on the kebab menu is also a good option to change an existing disk without having to turn on edit, click bootable and then save it. Shouldn't be much work to do both. Same amount of work on the create saga either way.

Please note that in case you want to set the bootable option via the kebab menu, you will need two interchangeable menu entries that are switched based on current VM status: bootable/un-bootable, so I'm not sure if it's more user friendly than adding a column. Don't forget that only one disk can be set as bootable per a VM. So in case there is an already existed bootable disk, only this disk can be set as "unbootable" while others are blocked for the bootable option. In case the bootable disk is a template's disk then nothing can be changed for other disks as well (at least for now when we still can't edit disk's templates). The user somehow should be aware of why the bootable options are disabled/enabled. When we have a dedicated column, it seems more easy to add a tooltip for explaining.

**Comment by hstastna** [comment]
@sgratch @lwrigh @michalskrivanek @sjd78
Just to make sure, do we want to see the Bootable column like this when editing/adding new Disk?
![expected](https://user-images.githubusercontent.com/13417815/84253138-daaf4480-ab0f-11ea-8633-eb5ba723243b.png)

**Comment by hstastna** [comment]
There's another thing which worries me:
When looking from the VM itself on Disks, the Disks can be identified by either some ordering or by id. I am not aware of possibility to access names (which are displayed in the VM Portal) of Disks from within the VM. But in VM Portal, we don't display such id and we also change the order of Disks using sort function [here](https://github.com/oVirt/ovirt-web-ui/blob/master/src/components/CreateVmWizard/steps/Storage.js#L475). So I think it may be problematic to recognize which Disks we work with. Maybe we should display the id or not change the order of Disks (of course only if we don't get Disks to display in the UI in some random order). However, in webadmin, we display the id in _Storage > Disks_, in the ID column (but it's not displayed when viewing a specific VM and its Disks and I think it's missing there). The situation is even worse when we allow to create Disks with the same name in the same VM (both webadmin and VM Portal).

**Comment by hstastna** [comment]
Another question:
Is a situation with none of the Disks set as bootable valid? I think it should be ok (maybe we could boot from network), but I'm not sure. Thanks! :sparkle:

**Comment by sjd78** [comment]
> Another question:
> Is a situation with none of the Disks set as bootable valid? I think it should be ok (maybe we could boot from network), but I'm not sure. Thanks! sparkle

Technically yes.  But at runtime with multiple disks, I don't know which one gets picked up as bootable.
