### ISSUE TITLE
Create VM Wizard - cannot tab through edit fields on Networking and Storage steps

### ISSUE THREAD

**Issue by sjd78** [oVirt/ovirt-web-ui#1248]
>
> 5. you can only reach first input in the row by Tab key
>

Yep - that's partially due to the way the table uses `onBlur` to update values.  Also, that would be easier solved in another issue as it applies in both Storage and Network tabs.

_Originally posted by @sjd78 in https://github.com/oVirt/ovirt-web-ui/pull/1221#issuecomment-656342168_

The Networking and Storage steps should allow users to tab between the active input fields when creating or editing a Nic or Disk.

Since `onBlur` is used to update the field values, the change event handlers would probably need to be updated to allow navigation.

**Comment by bamsalem** [comment]
Hi guys,
@sjd78 @sgratch @hstastna @rszwajko 
I'm working on this issue and I have few things that I want to rase:

1. Double click issue: if one of the fields is focused to focus another field the user need to double click it:
![doubleClickCreateVmWizardField-2020-07-22_12 02 33](https://user-images.githubusercontent.com/64131213/88158257-7d310c00-cc14-11ea-849f-4e60e427dde0.gif)
it happens because we using onBlur event, There have been many discussions on that on #1221 issue, and this is Scott's  [explanation](https://github.com/oVirt/ovirt-web-ui/pull/1221#issuecomment-660606958)

2. Move between dropdown options using keyboard: if one of the dropdown fields focused and the user hit the "space key" the drop down options appear as expected but when he tries to move between the options nothing happened:
![dropDownOptionsSwitch-2020-07-22_12 30 44](https://user-images.githubusercontent.com/64131213/88172831-42d26980-cc2a-11ea-89c3-b938fd4c3050.gif)

I'm not sure that those issues included in this issue or if they should be handled in another issues.
WDYT?

**Comment by sjd78** [comment]
> I'm working on this issue and I have few things that I want to raise:
> 
>     1. Double click issue: if one of the fields is focused to focus another field the user need to double click it:
>        it happens because we using `onBlur` event, There have been many discussions on that on #1221 issue, and this is Scott's  [explanation](https://github.com/oVirt/ovirt-web-ui/pull/1221#issuecomment-660606958)
> 

So it's caused by the same problem as trying to Tab through the fields - onBlur() causes the table to re-render and the input field gets reset/unfocused.  If there is a reasonable solution to the tabbing issue, this problem would probably be resolved also.

>
>     2. Move between dropdown options using keyboard: if one of the dropdown fields focused and the user hit the "space key" the drop down options appear as expected but when he tries to move between the options nothing happened:
> 

It is already known, see #585.  Basically we'd need to switch out the component to a new component that supports keyboard input properly.  But that work is already marked won't fix, so don't worry about it anymore.

**Comment by hstastna** [comment]
I think those are slightly different issues but related to edit fields on Networking and Storage steps, too. And of course, the more things you will be able to fix, the better. But regarding the `onBlur`, it may be problematic, as we've found. But maybe we don't have to be perfect, at least for now :)
