### ISSUE TITLE
Different margin of fields in the Storage step when adding vs. editing Disk

### ISSUE THREAD

**Issue by hstastna** [oVirt/ovirt-web-ui#1250]
**Description of a problem:**
There's an inconsistency between displaying the Disk row in the _Storage step_ of the _Create VM Wizard_ when adding vs. editing Disk. The margin of the fields/drop downs in the row _looks_ slightly different. The difference is visible and little bit annoying especially when user adds a new Disk and tries to edit the Disk right after creating it.

**Browser and version:**
FF 78, Chromium, Google Chrome 83
(probably also older versions of the browsers)

**Steps to Reproduce:**
1. Click on the _Create Virtual Machine_ button
2. Go through the first two steps
3. In the _Storage step_, click on the _Create Disk_ button and see how the Disk row looks like (same as the _Expected result_ screenshot)
4. Save the new Disk and try to edit it by clicking on _Edit_ in the kebab menu (vertical **...**)

**Actual result:** 
Editing an existing Disk: the `margin-bottom` seems to be slightly increased:
![edit](https://user-images.githubusercontent.com/13417815/87339783-64a36080-c547-11ea-9eee-1bf259e2ffd6.png)

**Expected result:** (same as when adding new Disk)
![create](https://user-images.githubusercontent.com/13417815/87339795-6836e780-c547-11ea-8c76-a10d2dc5fde9.png)

**Comment by bamsalem** [comment]
After a brief inspection I found the cause to the difference, the difference between the options is the `kebab menu`:
![image](https://user-images.githubusercontent.com/64131213/88777159-90e9ee80-d18f-11ea-9afd-ee51a9a67f65.png)

I thought about two options to fix it:
1. Hide the kebab menu: the first option is to hide the kebab menu and to create consistency between create and edit mode, in addition it won't change the functionality because all the options are disabled:
![image](https://user-images.githubusercontent.com/64131213/88777474-ede5a480-d18f-11ea-8ac8-6c9ef8b45873.png)
The final result:
![image](https://user-images.githubusercontent.com/64131213/88777694-2be2c880-d190-11ea-9820-a7eaa1c93608.png)

2. Change the Padding values: the second option is to change the padding values and make it consist to create mode
![image](https://user-images.githubusercontent.com/64131213/88777778-487f0080-d190-11ea-9c21-c78856d0ee1d.png)

@hstastna , @sjd78 , @lwrigh , @rszwajko , @sgratch 
WDYT?

**Comment by hstastna** [comment]
@yfrimanm Hi Yifat, what do you think? Is it good to hide the kebab menu when we don't need it or better to fix the issue by changing the padding values as Ben has suggested above? Thanks! :)

**Comment by matthewcarleton** [comment]
@hstastna I would suggest never hiding the kebab menu (even if the values are disabled). I would lean towards just adjusting the spacing to keep the visuals consistent.

**Comment by sjd78** [comment]
Looks like it happens in both the Network and Storage steps.

Also, I'd just go the route of adding a spacer element to the create row to push the height up, and then make sure all of the form fields are vertically centered in the row.  It's really the 4px top and bottom padding on the kebab's button that is making the non-create rows a little bit taller.

**Comment by bamsalem** [comment]
> Also, I'd just go the route of adding a spacer element to the create row to push the height up, and then make sure all of the form fields are vertically centered in the row.

@sjd78 IMHO we should fix the different row heights and not add a spacers, there is no reason to use spacers because in case of doing that we should add spacers to other rows like template defined rows:
![image](https://user-images.githubusercontent.com/64131213/89294239-e4fd4300-d667-11ea-9a88-3fc7439dc86f.png)

I think that better solution is to edit the Kebab's Cell padding value:

create:
![image](https://user-images.githubusercontent.com/64131213/89294576-5dfc9a80-d668-11ea-99f3-c398d49d04e7.png)
edit:
![image](https://user-images.githubusercontent.com/64131213/89293886-55579480-d667-11ea-8b28-aa69379c4524.png)
view:
![image](https://user-images.githubusercontent.com/64131213/89293845-42dd5b00-d667-11ea-935c-8006c74203f1.png)

@hstastna @rszwajko @yfrimanm WDYT?

**Comment by sjd78** [comment]
@bamsalem - So...adjusting the spacers, but in a different way?  ;-)

I'd prefer to see a bit more of padding around the row contents by making that last column's icon / lack of icon all the same size.

**Comment by matthewcarleton** [comment]
I agree. We should be setting row heights with padding and not a fixed height for better accessibility. All rows should meet the maximum height requirements for the row when considering the different elements that will exist in the row at any given time.
