### ISSUE TITLE
VM Portal Create New VM from Template not moving from Basic Settings

### ISSUE THREAD

**Issue by girid333** [oVirt/ovirt-web-ui#1270]
Hi All,

I am using Ovirt 4.4.1, the engine and Node setup is complete and i am able to create VM's from engine admin portal.

Once VM's created i have performed Sysprep for both Windows and Linux versions and converted the VM's as QCOW2 template.

Now when i try to create new VM using template from VM portal i coud not move ahead from Basic Settings page even if we have provided all inputs for the mandatory fields still the Next button is greyed out and not appear for clicking next.

![image](https://user-images.githubusercontent.com/57260105/90380351-943f0e80-e099-11ea-8baf-8106b24260fd.png)

VM Portal version number: 1.6.3-1

oVirt version number: 4.4.1

Browser and version: Google Chrome Version 84.0.4147.125

Steps to Reproduce:
1. Open VM portal 
2. Click Create Virtual Machine Wizard
3. Provide all inputs

Actual results:
Next button is not Visible for next Step

Expected results:
Next button to be Visible for next Step

**Comment by sgratch** [comment]
@girid333 can you please specify what is the "cloud-init options" -> 'Hostname' field value that you are using?

The 'Hostname' field value entered must be at least one character long and may contain only 'a-z', '0-9', '_', '.' or '-' characters only. Is this the case for you?

It seems that we are currently having a bug with the validation of this field since:
1. Not all mentioned chars are allowed as it should.
2. In case of a validation error, the field is not marked in red. @bamsalem is this fixed as part of  #1251?

**Comment by girid333** [comment]
Thank you sgratch for the reply. The issue is now resolved.

Actually when i drop down the cluster field and selected the default once again then all options start to get visible.
It is strange that a predefined value is not taken by the portal even though only one cluster is available.

**Comment by sgratch** [comment]
> Thank you sgratch for the reply. The issue is now resolved.

Thanks, so I'm closing this issue. 

> Actually when i drop down the cluster field and selected the default once again then all options start to get visible.
> It is strange that a predefined value is not taken by the portal even though only one cluster is available.

This will be implemented by issue #1252
