### ISSUE TITLE
Add NIC fields validation for adding/editing NICs in the VM Network interfaces card

### ISSUE THREAD

**Issue by hstastna** [oVirt/ovirt-web-ui#1294]
Related sources:
https://github.com/oVirt/ovirt-web-ui/pull/1219#issuecomment-693186404
https://github.com/oVirt/ovirt-web-ui/issues/1205

Frontend validation of NIC fields (especially name), for adding/editing NICs in the _Network interfaces_ card of an existing VM, should be added, similarly as it was already done for CreateVmWizard here: https://github.com/oVirt/ovirt-web-ui/pull/1219
![nics](https://user-images.githubusercontent.com/13417815/93332864-c8d1f180-f822-11ea-9f65-24417ffb9462.png)

**Comment by sgratch** [comment]
@hstastna I prefer to avoid that and let the backed do the validations to avoid duplicated validations logic/code.
The only reason we added basic validations for CreateVmWizard is since it's a wizard with few steps. 
We want to avoid a user experience of setting few steps, applying and then realizing that there is a validation error on backend and all his previous settings steps are gone. This is not the case for VM's cards that has only one step of configuration.

**Comment by sgratch** [comment]
Therefore I suggest to close this issue.
