### ISSUE TITLE
Required fields Cluster and Operating system not validate while creating a VM

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-web-ui#1353]
Description of problem:
while re-testing issue #1207 with oVirt 4.4.4 I saw that despite I didn't add any host I had "Create Virtual Machine" button enabled. I think this is a bug on its own but assuming this is by design I tried it.
In opposite to what happened back in #1207 now the "Next" button is enabled even if mandatory fields Cluster and Operating system are not set.
![Schermata da 2020-12-21 17-27-53](https://user-images.githubusercontent.com/937860/102799215-80dae180-43b2-11eb-9468-3fe3cf26b415.png)

You can continue through the wizard till the last page when then it fails:

![Schermata da 2020-12-21 17-32-48](https://user-images.githubusercontent.com/937860/102799347-b1bb1680-43b2-11eb-92a2-5b3022ac6ff8.png)

It should have blocked the user on the first page when the mandatory fields were missing.

VM Portal version number: Version 1.6.6-1
oVirt API Version 4.4

oVirt version number: 4.4.4

Browser and version:Google Chrome 87.0.4280.66

Steps to Reproduce:
1. install oVirt Engine
2. access vm portal
3. Try to create a VM

Actual results: wizard doesn't block you on missing required fields

Expected results: wizard should block you

Additional info:

**Comment by hstastna** [comment]
@sandrobonazzola Maybe this already existing issue is related: https://github.com/oVirt/ovirt-web-ui/issues/1307

**Comment by sgratch** [comment]
This was reproduced to me as well and it's not related to https://github.com/oVirt/ovirt-web-ui/issues/1307.

When there is only one cluster existed and no hosts were assigned to it yet (cluster's architecture and cpu-type are undefined) then the clusters list is empty so nothing to choose of and OS list is empty as well but the next button is enabled. 
This should have been fixed by https://github.com/oVirt/ovirt-web-ui/pull/1318#issuecomment-725383913 (displaying "There are no available clusters" label and next button should be disabled )but somehow it's not working.
I'll assign it to @bamsalem for checking.
