### ISSUE TITLE
Ovirt VM portal

### ISSUE THREAD

**Issue by abderaouf93** [oVirt/ovirt-web-ui#1555]
Hello to everyone,

I would like to ask, if there is a way in order to split the VM portal user login screen, From the one shared between the user portal and web admin.

thank you in advance,
Regards.

**Comment by sgratch** [comment]
Hi @abderaouf93 
Each portal has it's own url, so you don't have to go through the oVirt welome page and reach each one of them directly, e.g.: 
[https://server/ovirt-engine/webadmin/](https://server/ovirt-engine/webadmin/) - for Admin Portal
[https://server/ovirt-engine/web-ui](https://server/ovirt-engine/web-ui/) - for VM portal

But both use the same SSO login dialog since users management is the same.
If you want to separate them by FQDN then it's not supported by oVirt since all should use the engine FQDN for accessing the engine. You can probably use your own customized URL redirection but I won't recommend it.

Regarding user permissions to login, login will fail if a regular user won't have permissions to login to webadmin. This deals with user permissions management that should be set correctly.
