### ISSUE TITLE
reconsider the door effect

### ISSUE THREAD

**Issue by jelkosz** [oVirt/ovirt-web-ui#156]
When a VM cube is picked, a door effect slides the VMs to the left side and the right side of the screen is filled with the VM details.

This behaviour is a more eye-candy implementation of the original basic user portal which behaves similarly without the door effect.

The biggest advantage of this UI is that it makes use of a large part of the screen (about a half of it) and scales well with the size of the screen. 

The disadvantage is that the design is quite controversial and also not in line with the patternfly which is used by other UIs of the oVirt ecosystem (like cockpit plugin or webadmin).

I would propose to use a similar approach as the trello is using when opening a card. Don't slide anything enywhere, open a large (patternfly) dialog window in the centre of the screen which will be proportional to the size of the screen (e.g. also will take about half of it and will scale with the size of the screen).

It will have all the advantages of the original design but will be more in-line with the patternfly (meaning the rest of the ecosystem) and will be less controversial.

@mareklibra @jniederm @matobet @bond95 @michalskrivanek what you guys think?

---------
Fixed by:

 - https://github.com/oVirt/ovirt-web-ui/pull/197

Depends on:

 - #200 
 - #196

**Comment by matobet** [comment]
Big :+1: to a modal, patternfly-aligned dialog. The door effect is just too .... controversial.

**Comment by mareklibra** [comment]
I prefer the dialog style over the sliding effect more.
Anyway, let's put this on hold for a while. Maybe we find something even better.

**Comment by jniederm** [comment]
It seems that web-ui proved itself a viable product and it's gaining more and more features. I find this stage of development the right moment to create a vision of intended "final" state. Maybe we will want the project to cover more than just functionality of current basic user portal. In that case it may be handy to think through the "complete" version is supposed to look like, what kind of data we will want to show and edit. How to visually represent content of current subtabs or navigation to listings of other entities (e.g. templates or perhaps hosts).

Such vision can help us to prevent current problems of webadmin like:
* it is difficult to search for editing widget or particular name - there is no in-app search and standard "Ctrl-F" doesn't work because of side-tabs
* it is quite tedious, sometimes even impossible to find out what is value of running VM configuration and what is value of next-run configuration
* if backend validation fails, changes of whole VM dialog are lost
* some operations a represented in rather unfortunate way, for example memory hot plug
* Quota tab - the easter-egg

Regarding potential door replacements: I find following ways worth considering:
* modal dialog (similar to current webadmin)
* just removing the door effect and enlarging  the VM detail space to, let's say, 90% of viewport width
* separate "page" for VM detail. Used by Cockpit (e.g. Accounts or Container). Space efficient. My most favorable.

**Comment by jelkosz** [comment]
I also agree with aligning us with the design as is in cockpit and manageiq and maybe will also be in webadmin one day.

So, based on Jakub's proposal:
- having a left pane similar to cockpit or openshift containing the entities we present (e.g. VMs, Templates). Will look like: http://www.mastertheboss.com/images/stories/vari/openshift/origin1.png
- if a specific VM is picked, replace the visual area with it (no door effect)
- add a breadcrumb similar to the one cockpit is using
- when new and new fields will be added to the VM detail page, they will all be in that one page organized in boxes (similar to manageiq) where the user can use e.g. ctrl+f to find something

all agree?

**Comment by gregsheremeta** [comment]
Fyi, there is prototype work going on in webadmin (UX group) to eliminate all dialogs. It's atypical to use modals in patternfly. We're aiming for something more modern where managing an entity takes up the entire screen. Pretty much what Tomas was referring to in the previous comment.

Also, I don't care for the door effect. So +1 on the issue.

**Comment by bond95** [comment]
![screenshot from 2017-05-18 15-35-56](https://cloud.githubusercontent.com/assets/3332176/26204711/d9996be0-3bdf-11e7-82e4-2df709dfe0f0.png)
![screenshot from 2017-05-18 15-36-27](https://cloud.githubusercontent.com/assets/3332176/26204722/df8b018a-3bdf-11e7-8dc0-9b7734241ff1.png) @jelkosz @mareklibra @matobet  @gregsheremeta

**Comment by mareklibra** [comment]
I would swap the breadcrump with actions.

**Comment by mareklibra** [comment]
@bond95 , do you plan to introduce react-router? ;-)

**Comment by jelkosz** [comment]
> But how far? The left side menu looks weird when near-to-empty.
At least the templates will need to get in kinda soon.

**Comment by jelkosz** [comment]
@gregsheremeta if you compare it to the effort you mentioned, does it look similar? What are the main differences which you think should be changed/fixed in this effort?
