### ISSUE TITLE
Ovirt Web-portal Console Error Setting VM ticket failed.

### ISSUE THREAD

**Issue by abderaouf93** [oVirt/ovirt-web-ui#1569]
[ Thank you for submitting an issue to the VM Portal issue tracker. Please read these instructions and delete this section before submitting your issue. ]

[ If this is a bug report, use this section and delete the other one: ]

Description of problem [include screenshots and browser console logs]:

VM Portal version number: 4.4.10

oVirt version number: 4.4.10

Browser and version:

Steps to Reproduce:
1. Fresh install Ovirt 4.4.10 on HP DL380 Gen8
2. Access Web-Gui VM portal
3. Try use VM Console ( VNC/SPICE)

Actual results: Fail with the Following error : VDSM ********** command SetVmTicketVDS failed: General Exception: ('unsupported configuration: VNC password is 12 characters long, only 8 permitted',)

Expected results:

Use the Console with no errors

Additional info:

[ If this is a request for a feature or enhancement, use this section and delete the other one: ]

Feature enhancement request:
[ Describe the feature or enhancement you would like. Be as detailed as possible, including screenshots or links to design documents. ]

**Comment by sgratch** [comment]
This is a known issue on backend: since libvirt 8 [1], a warning appears when providing a ticket with a password with length over than 8.

A fix in engine will be introduced on oVirt 4.5: https://github.com/oVirt/ovirt-engine/commit/a1e7e39348550b575f1f01b701105f9e1066b09f.

Therefore, I'm closing this issue.
