### ISSUE TITLE
"undefined failed" shown in VM cube's error

### ISSUE THREAD

**Issue by jelkosz** [oVirt/ovirt-web-ui#192]
- login to web-ui
- wait until the entities are loaded
- restart engine (e.g. to loose the session)
- don't reload the web-ui, click start of some VM
- the user readable error message is shown on the VM cube (good)
- open the details of the VM
- close the details of the VM (instead of the user readable msg the undefined failed) is shown in the VM cube

Being fixed by https://github.com/oVirt/ovirt-web-ui/pull/194

**Comment by mareklibra** [comment]
Fix: "Failed to retireve VM details" is rendered

**Comment by mareklibra** [comment]
If the token is invalidated, like due to lost session, the easiest way to proceed is to reload the page so the oVirt SSO login page will be involved.

I see following options:
- user needs to press F5 or so
- error message is rendered providing action (like hyperlink) causing page reload
- or information message is rendered and the page is automatically reloaded with some delay (like 5 secs). User is able to cancel it within this time frame.

I think the second option is the best one from the UX perspective. What others think?

Detection of expired token requires internally an extra oVirt API call.

**Comment by mareklibra** [comment]
With recent implementation, following message is rendered:

    Authorization lost. The page is going to be reloaded to re-login.

and after next 5 seconds the page reload is issued.

**Comment by jelkosz** [comment]
@mareklibra yeah, that makes sense
