### ISSUE TITLE
VM detail labels tooltip is inconsistent with rest of UI

### ISSUE THREAD

**Issue by KwisatzHaderach** [oVirt/ovirt-web-ui#288]
Description of problem:
Tooltip on labels in VM detail in web-ui is not convenient, it is weird to have to click on labels to get help about them.
It will be a lot better to get the help right away on hover (tooltip).

Steps to Reproduce:
1. open web-ui
2. open VM detail

Actual results:
you need to click on label to get help about it

Expected results:
help appears after hover on label

**Comment by mareklibra** [comment]
This would be not working for tablets.

Idea: what about combined approach? 
It means, the tooltip is displayed when label is clicked **or** on hover after a small delay (like 0.5 sec).

The delay would solve issue with too much blinking when moving the mouse cursor over the screen.

What others think? @jniederm , @jelkosz

**Comment by jniederm** [comment]
I believe that currently state (click to see a popup) is pretty good. Once user get familiar with used options, the help is not needed any more and it isn't bothering since it requires a click.

Tooltips should be kept kept unobtrusive. Ways to do that: 

* small info icons (difficult to accidentally hover), + immediate hover popup, webadmin uses delayed hover
  * (+) very self-explanatory
  * (-) small active area - patternfly default icon is pretty small, usable with sufficient padding
* click label pupup, currently used
  * (+) large, easy to point by both mouse and finger
  * (-) underlying is not that self-explanatory and aesthetic
  * (-) laborious for often use
* delayed hover label popus
  * (+) large, easy to point by both mouse and finger
  * (-) underlying is not that self-explanatory and aesthetic

I tried both [patternfly][1] and [bootstrap][2] tooltips on my Android phone and it works good in both Firefox and Chrome. So we don't need to combine hover and click events for supporting touch devices.

My opinion: current state is good enough, I find infoicons + hover to be the best option, delayed hover + labels would be an improvement.

[1]: https://www.patternfly.org/pattern-library/widgets/#tooltip
[2]: http://getbootstrap.com/javascript/#tooltips

**Comment by mareklibra** [comment]
Related to #596

**Comment by gregsheremeta** [comment]
this will be overhauled in redesign, closing
