### ISSUE TITLE
Consider removing left sidebar

### ISSUE THREAD

**Issue by jniederm** [oVirt/ovirt-web-ui#312]
Based on Michal's suggestion, since there is currently no long-term plan to add other item into the left sidebar, and there is only one item there, let's consider removing it.

![image](https://user-images.githubusercontent.com/5278760/29219370-1d0c5444-7eb8-11e7-8f1a-e674331d1fd8.png)

**Comment by mareklibra** [comment]
Yes, it looks weird in this state.

Anyway, I would not remove it completely from the code since there might be `Templates` in the near (or mid-term) future.

And since everything is already prepared for it, I would either
 - render with 0 width
 - or better remove from rendering in React **along with adding a comment how to reenable it**

**Comment by jniederm** [comment]
@michalskrivanek, how is it with Templates, is this feature expected in mid-term future?

**Comment by michalskrivanek** [comment]
dunno. For now selecting one when adding VM seems to be enough. I'd go with removing it from gui, keep in code with comment

**Comment by jelkosz** [comment]
I agree - hiding it and letting it in the code sounds like a good option.
I think we could make it configurable in the config file - so if someone would pick the task of implementing the temlates, showing the left bar would be made visible using a config and not hacking the code.
