### ISSUE TITLE
no VMs to show got stuck on 'Loading ...'

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#331]
When I log to VM portal and no VMs are there (fresh install of engine). Loading ... got stuck and message 'No VM available.' shows after 1 minute. When I click on Refresh the message appears immediately.

tested in ovirt-web-ui-1.2.1-1.el7ev.noarch for rhvm 4.1.6

**Comment by suomiy** [comment]
The problem is this. loadInProgress is set to true by default. Vms are requested by rootSaga (this request does not change loadInProgress). If vms are returned then Vms.Component tries to download next page (this request changes loadInProgress to false at last). But if no vms are returned Vms.Component does not load more pages and loadInProgress stays set to true. This is reset by another poll after 1 min or refresh.
