### ISSUE TITLE
Make saga error handling more robust

### ISSUE THREAD

**Issue by mareklibra** [oVirt/ovirt-web-ui#450]
If any saga fails for whatever reason (including an exception), the application must stay in working state.

To verify, e.g. within a saga, use code like
```
   const dummy = undefined
   dummy.failHere()
```

Such a flow must be properly logged but the rootSaga must continue to live and process next actions.

**Comment by gregsheremeta** [comment]
@sjd78 is this still an issue?

**Comment by bond95** [comment]
@gregsheremeta GlobalErrorBoundary already implemented, can we close this issue?

**Comment by sjd78** [comment]
@bond95, @gregsheremeta - The error boundary is a good kernel panic trap, and it prevents the app to run with inconsistent state and prevent the app from being unloaded.  However, it isn't quite what the issue here is asking for.  I'm ok with closing this issue with the caveat that the App just fails to an error state, and I'm ok with leaving it open so we can circle back to provide a more self-healing approach.

**Comment by gregsheremeta** [comment]
> closing this issue with the caveat that the App just fails to an error state

Indeed.
