### ISSUE TITLE
error by adding new Network interface to VM

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#545]
When I add new network (vNIC from the same cluster that the VM) to VM. Network is added but error appears. Error in engine.log.
ADD_VM_NIC failed
Internal Server Error

tested in ovirt-web-ui-1.3.7-2.el7ev.noarch with ovirt-engine-4.2.2.5-0.1.el7.noarch

![screenshot from 2018-03-28 16-20-28](https://user-images.githubusercontent.com/29575480/38035368-9025f48a-32a4-11e8-934f-7f84e528ecf6.png)

**Comment by leistnerova** [comment]
engine log
[log.zip](https://github.com/oVirt/ovirt-web-ui/files/1856373/log.zip)

**Comment by michalskrivanek** [comment]
@bond95. ehh, why? how is console related?

**Comment by bond95** [comment]
@michalskrivanek console? There is problems with rights (Filter: true/false) on `engine`.

**Comment by jelkosz** [comment]
Should be fixed in most part by #550
The only way how to reproduce this issue after #550 will be merged will be by setting AlwaysFilterResultsForWebUi engine-config property to true. 
The https://bugzilla.redhat.com/show_bug.cgi?id=1551575 will fix also this case.

But if #550 fixes the basic issue, it will lower the priority of this bug significantly.

@bond95 can you please check?

**Comment by bond95** [comment]
Fixed by https://github.com/oVirt/ovirt-web-ui/pull/550.
