### ISSUE TITLE
unit test for Czech locale needs ICU data

### ISSUE THREAD

**Issue by mareklibra** [oVirt/ovirt-web-ui#557]
The full ICU was added in https://github.com/oVirt/ovirt-web-ui/pull/547 and reverted in https://github.com/oVirt/ovirt-web-ui/pull/556 .

To re-enable ICU in this project, the full-icu post-installation script introducing dynamic dependency on https://www.npmjs.com/package/icu4c-data needs to be resolved.

More info in https://github.com/oVirt/ovirt-web-ui/pull/556.

**Comment by sjd78** [comment]
@gregsheremeta - The unit test I added to verify the sort worked in another language (Czech actually) required using a library to install ICU data (for Czech).  Worked great in internet connected builds, but failed disconnected since the library downloads stuff (much like PhantomJS did).  Easiest fix was to revert and take that test and library out.

No progress has been made since with finding an alternative way to have ICU language data guaranteed available in node for use by node side scripts (testing being the most relevant one).

At this point, it is purely a nice to have.
