### ISSUE TITLE
user can't start VM (GET_ALL_VNIC_PROFILES failed) when no permission on the vnic profile

### ISSUE THREAD

**Issue by gregsheremeta** [oVirt/ovirt-web-ui#722]
Originally reported at https://bugzilla.redhat.com/show_bug.cgi?id=1562108

Description of problem:

In oVirt 4.2.1 there was a bug that a user who had UserRole permissions on a datacenter (and all of its vm's) could not see the VM's in the new VM portal.

This seems to be fixed in 4.2.2. However the user can still not start the VM's and receives the following error:

GET_ALL_VNIC_PROFILES failed
query execution failed due to insufficient permissions

Version-Release number of selected component (if applicable):
4.2.2.5-1.el7

How reproducible:

Steps to Reproduce:
1. Assign UserRole permissions to a user on a datacenter/cluster
2. Log in to the vm portal as that user
3. Try to start/stop a VM.

Actual results:
Fails with the error described above

Expected results:
VM is started/stopped

Additional info:

**Comment by sjd78** [comment]
This sounds similar to the issue with accessing a VM console from REST (#509).  Essentially, when the REST endpoint was attempting to follow a link (in that case to return the user who owned the console session), the link's entity was not accessible to the user doing the request and the entire request failed.  
That solution was to have the REST endpoint updated so the link would be returned if the user doesn't have permissions to the entity the link references.

So I wonder 2 things:

 1. Do the stop and start buttons from the VM card list page throws the same error?  The fetch done for the list page doesn't ask the REST endpoint to follow any links, and the REST call to start/shutdown a VM only includes the `vmId` as input.

 2. What happens when the user clicks on the VM to open the detail page? The details fetch does include an extra `follow` and nics is one.  This may not be a problem. Worst case is the page only shows the minimal details (from the VM list view). Best case is that the entities the VM links to that the user doesn't have permissions for will not render.  Following that, same as in the VM card list page, the REST call for start/shutdown only includes the `vmId` as input.

Given those 2 pathways, it's difficult to see where the problem could be in web-ui itself.

**Comment by michalskrivanek** [comment]
@gregsheremeta @sjd78 I get that error now in 1.4.2 even when just logging in. No start/stop. I have a PowerUserRole on some DCs, not all of them.

**Comment by michalskrivanek** [comment]
also cc @bond95

**Comment by bond95** [comment]
@gregsheremeta @sjd78 @michalskrivanek could you, please, check again? Cause on Engine 4.2.6.4-0.1.el7ev and VM Portal 1.4.2-1 (TLV engine), I have no errors. But previous I had that error on TLV.

**Comment by gregsheremeta** [comment]
yep, just duplicated on brq with test non-admin user (happens on login)

**Comment by michalskrivanek** [comment]
@sjd78 @gregsheremeta @bond95 try UserRole on a vNIC profile, but without VnicProfileUser on it
(on brq-dev that's currently vnic profile "petrovasit") 
@phoracek I know it's your's, but please do not touch permissions there until we fix it:)

**Comment by k0ste** [comment]
On 4.2.7 is still reproducible.

**Comment by bond95** [comment]
@gregsheremeta Can it be closed, because BZ is already in VERIFIED state? https://bugzilla.redhat.com/show_bug.cgi?id=1654442

**Comment by gregsheremeta** [comment]
yep thanks :)
