### ISSUE TITLE
Filter clusters according to permits, not roles

### ISSUE THREAD

**Issue by bond95** [oVirt/ovirt-web-ui#811]
User can create own roles, thus need to filter clusters according to permits, not roles, because permits are static and can't be changed or added new one by user.

**Comment by sjd78** [comment]
**Note**: The merged solution, PR #784, to issues #745 / [BZ1597705](https://bugzilla.redhat.com/show_bug.cgi?id=1597705) and #737 / [BZ1599617](https://bugzilla.redhat.com/show_bug.cgi?id=1599617) relied on Permissions and not on Permits.  This issue changes the base unit of authorization checking from Permissions to Permits themselves.

The two BZs will need to be re-tested once this issue is resolved by PR #813.  I'll update them to reflect the current situation.

**Comment by sjd78** [comment]
Reopening since the merge of #836, which depends on #813, should have waited for #813.  My mistake.
