### ISSUE TITLE
VMs disk is created as Thin instead of Clone when template is optimized for server

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#882]
Steps to reproduce:
1. in admin portal create template from VM with disk
2. set Optimized for: Server on the template
3. log into VM portal, create new VM from that template

VM is created with <format>cow</format> disk but it should be raw.

By creating VM it should sent &lt;clone&gt;true&lt;/clone&gt; when template is optimized for server (according to admin portal functionality when it automatically changes Storage Allocation depending on 'Optimized for' value).

**Comment by SIN3R6Y** [comment]
I would suspect the issue is here, https://github.com/oVirt/ovirt-web-ui/blob/5a694b8422cfbc3441a16e2dc9189aa8ab2acd6b/src/components/VmDialog/index.js#L204

IIRC if you don't specify whether to make a dependent or independent disk, it defaults to dependent when this should not be the case for "server" templates.

**Comment by michalskrivanek** [comment]
yes, exactly
https://github.com/oVirt/ovirt-engine-api-model/blob/12ec843f5c4486cb878d38ecf47edcccf095ba61/src/main/java/services/VmsService.java#L228
