### ISSUE TITLE
UserSessionTimeOutInterval key doesn't take effect on VM Portal

### ISSUE THREAD

**Issue by gregsheremeta** [oVirt/ovirt-web-ui#955]
Originally reported at https://bugzilla.redhat.com/show_bug.cgi?id=1667489

UserSessionTimeOutInterval for engine-config is used to set timeout interval in minutes, after which inactive user sessions expire. It doesn't take effect for VM Portal, but works perfectly for Admin Portal.

See also #598

**Comment by sjd78** [comment]
> UserSessionTimeOutInterval for engine-config is used to set timeout interval in minutes, after which inactive user sessions expire. It doesn't take effect for VM Portal, but works perfectly for Admin Portal.

We use the same SSO token (with the same grant type and scope) for all of the REST calls.  So the background data update task cannot be differentiated from real user generated traffic.  The token will never expire like that.  The REST calls would need to have some kind of HTTP request header available to instruct SSO token validation not to update the last access date.  I have no idea if that is currently an option.

**Comment by gregsheremeta** [comment]
> I have no idea if that is currently an option.

@noriravi what do you think?

**Comment by noriravi** [comment]
Currently all restapi queries will update the last access date, we would need to modify the restapi code and backend code to achieve what is requested here. I would suggest opening a BZ.

**Comment by gregsheremeta** [comment]
> Currently all restapi queries will update the last access date, we would need to modify the restapi code and backend code to achieve what is requested here. I would suggest opening a BZ.

Thanks! @sjd78 can you open the BZ and describe what we need? team = infra  Thanks!

**Comment by gregsheremeta** [comment]
[ blocked by REST API enhancements needed ]

**Comment by michalskrivanek** [comment]
@sjd78 are you sure about the same scope for all queries. Some time ago when iportal was timing out for everyone, iirc we made a differentiation for the refresh andnother calls. Or maybe we just wanted to and didn’t do it, i don’t quite recall

**Comment by sjd78** [comment]
@michalskrivanek - As I understand how the SSO works, the scope and grant type are correlated to the SSO token at the time the token is created (so login box time).  The REST code all uses the same SSO token either from the dev engine pulling it or passed from the wrapping WAR.  I also can't find any instances where API calls are made with custom headers other then content types and "Filter".

So as long as the scope for a single SSO token is constant, then yes, all the requests use the same scope.

**Comment by michalskrivanek** [comment]
Ok, them we omly wanted to do that but didn’t:) right, it’s #308   I do not understand why we ended up using ovirt-app-api and not ovirt-app-portal scope

**Comment by noriravi** [comment]
Michal is right, if you obtain the token using ovirt-app-portal scope the last access date is not updated on restapi calls for that token.

**Comment by michalskrivanek** [comment]
@noriravi yes, but AFAICT from the code it's not doing anything right now - QueriesCommandBase::executeCommand() updates session time when 
getParameters().getRefresh() || SessionDataContainer::isSsoOvirtAppApiScope() which is set by
  scopes.contains(OVIRT_APP_API_SCOPE) && 
    !scopes.contains(OVIRT_APP_ADMIN_SCOPE) &&
    !scopes.contains(OVIRT_APP_PORTAL_SCOPE));

so...the portal scope currently behaves same as admin and then...does it just honor the refresh parameter? If yes we can just set it explicitly...

**Comment by michalskrivanek** [comment]
but if that doesn't work we can really just use a app-level timeout

**Comment by michalskrivanek** [comment]
@gregsheremeta @sjd78 
which is basically what #399 was opened for. So...just do that:-)

**Comment by sjd78** [comment]
@michalskrivanek, @noriravi - If the last access date in not updated on the token, won't it simply expire after the configured session timeout all the time?  So the token would only be good for say 15 minutes and then require a re-login?  Or is there another SSO call that we can pulse to keep the session alive?

One more question - is it possible to use a SSO token to grab a new derived SSO token with a different scope and use that derived non-refreshing token for the background refresh?

**Comment by noriravi** [comment]
We have 3 scopes on engine side. 

ovirt-app-api scope for restapi. Tokens obtained using this scope when used to execute a query will always refresh the last access date. This was intended to be used by SDK which always closes the connection and performs a logout which terminates the session. 

ovirt-app-admin scope for webadmin: Tokens obtained using this scope when used to execute a query will only refresh the last access date when the webadmin constructs the QueryParameters and set refresh to true. This works very similar to ovirt-app-portal scope. Only a period of inactivity will close the session.

ovirt-app-portal scope for UserPortal: Tokens obtained using this scope when used to execute a query will only refresh the last access date when the UserPortal historically constructed the QueryParameters and set refresh to true.

Any "action" executed using a token obtained using any of the 3 scopes will refresh last access date.

Issues with restapi:
We do not have a way to set "refresh" to true when using restapi since for SDK we always assumed SDK will logout after all the work is done.

Now if we want to use ovrt-app-portal scope to access restapi, the token will not get refreshed and will expire after 30 minutes. If we would like to have more control over when the session expires or some how would like to refresh the session we have 2 options. Both require code changes

1. Add ability to send "refreshToken" parameters with restapi calls. This requires touching restapi code and would be an RFE

2. Execute an action in the backend with the token obtained with ovrt-app-portal scope. This will refresh the last access date. I can add a simple RefreshTokenLastAccessDateCommand or KeepSessionAliveCommand which will set the last access date. The action needs to execute once every 29 minutes (session expires in 30 minutes) to keep the session alive. Much simpler to implement.

@michalskrivanek 
Yes ovirt-app-admin and ovirt-app-portal work the same way. We have no way to send refresh via restapi. We need to construct QueryParameterBase and set the value to true to pass it. 

@sjd78 

We cannot use a SSO token to grab a new derived SSO token

**Comment by sjd78** [comment]
> We have 3 scopes on engine side.

Thanks for the summary, very much appreciated.

> 2. Execute an action in the backend with the token obtained with ovrt-app-portal scope. This will refresh the last access date. I can add a simple RefreshTokenLastAccessDateCommand or KeepSessionAliveCommand which will set the last access date. The action needs to execute once every 29 minutes (session expires in 30 minutes) to keep the session alive. Much simpler to implement.

I like this approach.  `web-ui` can pulse the keep alive as needed and be able to give a count down timer to auto log off.  I'll create a BZ to get that service created.

> @sjd78
> 
> We cannot use a SSO token to grab a new derived SSO token

That is what I suspected, thanks for confirming.

**Comment by michalskrivanek** [comment]
You could also implement app-side timeout and just track time within ovirt-web-ui and discard token when exceeded. It’s kind of redundant to the potential engine side change, but OTOH it keeps the logic and control in one place

**Comment by sjd78** [comment]
> You could also implement app-side timeout and just track time within ovirt-web-ui and discard token when exceeded. It’s kind of redundant to the potential engine side change, but OTOH it keeps the logic and control in one place

Ok, it took me awhile to sort out what you're saying, but I think I'm there now.  Easiest solution looks to be to add user activity detection to the app.  If the app thinks the user hasn't interacted for an amount of time, follow the session timeout pattern ([patternfly pattern description](https://www.patternfly.org/pattern-library/communication/session-timeout/), [patternfly-react3 impl](https://rawgit.com/patternfly/patternfly-react/gh-pages/patternfly-3/index.html?knob-Active%20Step%20Index=0&knob-With%20Secondary%20Button=true&knob-content=Enter%20the%20hostname%20in%20a%20valid%20format%20%3Cbr%3E%20%20%3Ca%20target%3D%22_blank%22%20href%3D%22http%3A%2F%2Fwww.test.example.com%22%3EClick%20here%20for%20examples%20of%20valid%20hostnames%3C%2Fa%3E&knob-Bordered=true&knob-primary%20content=Your%20session%20is%20about%20to%20expire&knob-Loading=true&knob-Selection%20Type=none&knob-Close%20Popover=true&knob-Edit%20whole%20table=true&knob-With%20Secondary%20Content=true&knob-animate=true&knob-displayBefore=30&knob-timeLeft=30&knob-Show%20Help=true&knob-Placement=top&knob-Icon=info&knob-Root%20Close=true&knob-Field%20Level%20Help%20Content=Please%20specify%20Country%20code%20%3Cbr%3E%20%3Ca%20target%3D%27_blank%27%20href%3D%27https%3A%2F%2Fcountrycode.org%2F%27%3EClick%20here%20for%20a%20list%20of%20Country%20codes%3C%2Fa%3E&knob-fluid=true&knob-With%20Title=true&knob-secondary%20content=to%20continue%20click%20on%20%22Continue%20Session%22.&knob-Field%20Label=Hostname&knob-Size=default&knob-With%20Primary%20Content=true&knob-Match%20Height=true&knob-On%20Color=primary&knob-Style=primary&knob-Off%20Color=default&knob-With%20Icon=true&knob-ShowClearfix=true&knob-Label=Well%20done%21%20You%20successfully%20read%20this%20important%20alert%20message.&selectedKind=patternfly-react%2FCommunication%2FSession%20Timeout&selectedStory=Session%20Timeout&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)) and give the user a count down to logout timer w/ 1 minute remaining.  When the timer expires, make the call to invalidate the SSO token and push the user back to the login page.

If we change the SSO token scope, we would need the mechanism to keep the token alive while the user is navigating the app.  Leaving the scope alone lets us handle it ourselves in the react app.

*NOTE*: We should probably query a configured user session/inactivity timeout from the server.  I'm not sure if one exists that we can reuse or if we should create a new one just for web-ui.  Either way, that's an easier part of the work.
