### ISSUE TITLE
VM properties missing in VM portal

### ISSUE THREAD

**Issue by rdkdd** [oVirt/ovirt-web-ui#985]
Description of problem:
There are no VM properties in 4.3 RHV VM portal.
![screenshot from 2019-03-08 15-51-42](https://user-images.githubusercontent.com/18483085/54035673-35921780-41ba-11e9-9358-3b43fa68d1d6.png)
like in previous 4.2 RHV VM portal
![screenshot from 2019-03-08 15-59-26](https://user-images.githubusercontent.com/18483085/54036584-43489c80-41bc-11e9-85f4-8a8eee3df11a.png)
I mean those settings:

- Connect automatically
- Fullscreen
- Use Ctrl+Alt+End
- Smartcard enabled

VM Portal version number: 1.5.1-1
oVirt version number: ovirt-engine-4.3.2-0.1.el7.noarch
Browser and version: firefox-60.5.1-1.el8.x86_64

Steps to Reproduce:
1. Go to VM portal and select any VM
2. Try to modify any VM properties

Actual results:
no VM properties to set. User is for example unable to connect to VM in fullscreen since `fullscreen=0` by default in .vv-file

Expected results:
VM properies settings are available in VM portal.

**Comment by lwrigh** [comment]
@rdkdd We're currently in the middle of doing a redesign of the VM console page and looking to relocate these settings to the console page. Here are some of the wireframes that feature the console settings relocated to the console page instead of when you are editing individual VM settings. 

Console settings wireframes: 
![Individual Console Settings 1](https://user-images.githubusercontent.com/20227374/54698992-9bf62e80-4b06-11e9-981e-d1e0ad549cd8.png)
![Individual Console Settings 2](https://user-images.githubusercontent.com/20227374/54698999-9e588880-4b06-11e9-86fd-5dda0ff3d06d.png)

Feel free to leave any feedback or comments you have!

**Comment by bond95** [comment]
Will be fixed with new settings dialog 
![image](https://user-images.githubusercontent.com/3332176/57453841-b4153f00-7267-11e9-83d6-3215b25ad323.png)

https://github.com/oVirt/ovirt-web-ui/issues/145

**Comment by yodem** [comment]
@bond95 Is it still relevant?

**Comment by bond95** [comment]
@yodem yes, it will be fixed in https://github.com/oVirt/ovirt-web-ui/pull/1088

**Comment by sgratch** [comment]
This PR was addressed by https://github.com/oVirt/ovirt-web-ui/pull/1446 for oVirt 4.4.7
And few gaps are planned to be addressed by: https://github.com/oVirt/ovirt-web-ui/issues/1458 and https://github.com/oVirt/ovirt-web-ui/issues/1459.

Therefore I'm closing this issue as Done.
